INSERT INTO tb_user (name,email,password) VALUES ('Bob','bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name,email,password) VALUES ('Ana','ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

insert into tb_genre(name) values('Ação');
insert into tb_genre(name) values('Terror');
insert into tb_genre(name) values('Ficção');
insert into tb_genre(name) values('Drama');

insert into tb_movie(title,sub_title,synopsis,year,img_url,genre_id)values('Mad Max','Estrada da Fúria','Em um mundo pós-apocalíptico, Max Rockatansky acredita que a melhor forma de sobreviver é não depender de ninguém. Porém, após ser capturado pelo tirano Immortan Joe e seus rebeldes, Max se vê no meio de uma guerra mortal iniciada pela Imperatriz Furiosa, que tenta salvar um grupo de garotas. Também tentando fugir, Max aceita ajudar Furiosa.',2015,'https://i.pinimg.com/originals/d2/97/ef/d297ef138ada728e62a6ba3af4cb734b.jpg',1);
insert into tb_movie(title,sub_title,synopsis,year,img_url,genre_id)values('Cloud Atlas','Tudo está conectado','Várias histórias são desenroladas em diferentes linhas de tempo, mas mesmo sendo independentes e se desenvolvendo ao longo de cinco séculos, todas estão relacionadas e algumas têm impacto sobre outras, entrelaçando drama, mistério, ação e amor',2012,'https://cdn.suwalls.com/wallpapers/movies/cloud-atlas-15499-1920x1200.jpg',4);
insert into tb_movie(title,sub_title,synopsis,year,img_url,genre_id)values('Jurassic Park - I','Parque dos Dinossauros','Os paleontólogos Alan Grant, Ellie Sattler e o matemático Ian Malcolm fazem parte de um seleto grupo escolhido para visitar uma ilha habitada por dinossauros criados a partir de DNA pré-histórico. O idealizador do projeto e bilionário John Hammond garante a todos que a instalação é completamente segura. Mas após uma queda de energia, os visitantes descobrem, aos poucos, que vários predadores ferozes estão soltos e à caça.',1993,'https://cdn.hipwallpaper.com/i/56/16/AgsQwa.jpg',3);
insert into tb_movie(title,sub_title,synopsis,year,img_url,genre_id)values('Jurassic Park - II','O Mundo Perdido','John Hammond chama o teórico do caos Ian Malcolm à sua casa para dar algumas notícias aterradoras: enquanto quase tudo em Jurassic Park foi destruído, seus engenheiros parecem ter um segundo local, onde outros dinossauros estão escondidos. Aparentemente, os dinossauros na segunda ilha estão vivos e bem e até se acasalando. Hammond quer que Malcolm observe e documente as criaturas antes que mercenários cheguem até eles.',1997,'https://wallpapercave.com/wp/wp2900695.jpg',3);
insert into tb_movie(title,sub_title,synopsis,year,img_url,genre_id)values('Jurassic Park - III','','O agora famoso paleontólogo Alan Grant é convencido por um rico empresário e a mulher dele a realizar uma excursão aérea pela Ilha Sorna. Nela, dinossauros clonados vivem em liberdade e são estudados no ambiente natural. Mas um acidente com o avião faz com que o grupo de sete pessoas fique encalhado na perigosa ilha. Cercados por carnívoros famintos, os visitantes tentam escapar do lugar e salvar suas próprias vidas.',2001,'https://wallpaperaccess.com/full/2635202.jpg',3);
insert into tb_movie(title,sub_title,synopsis,year,img_url,genre_id)values('Donnie Darko','Why are you wearing that stupid man suit?','Donnie é um jovem excêntrico que despreza a grande maioria de seus colegas de escola. Ele tem visões, em especial de Frank, um coelho gigante que só ele consegue ver e que o encoraja a fazer brincadeiras humilhantes com quem o cerca. Um dia, uma de suas visões o atrai para fora de casa e lhe diz que o mundo acabará dentro de um mês. Donnie inicialmente não acredita, mas, momentos depois, a turbina de um avião cai em sua casa e ele começa a se perguntar qual é o fundo de verdade dessa previsão.',2001,'https://cdn.maioresemelhores.com/imagens/maiores-curiosidades-sobre-donnie-darko-og.jpg',2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Senhor dos Anéis: A Sociedade do Anel', 'A Terra Média ganha vida.', 2001, 'https://www.themoviedb.org/t/p/original/tdmlSbLl84hfHx635AqHLB8Qh8M.jpg', 'Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso, o hobbit Frodo tem um caminho árduo pela frente, onde encontra perigo, medo e seres bizarros. Ao seu lado para o cumprimento desta jornada, ele aos poucos pode contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando nove pessoas que formam a Sociedade do Anel.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Senhor dos Anéis: As Duas Torres ', 'A Sociedade é quebrada. O poder das trevas cresce.', 2002, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kWYfW2Re0rUDE6IHhy4CRuKWeFr.jpg', 'Após a captura de Merry e Pippy pelos orcs, a Sociedade do Anel é dissolvida. Frodo e Sam seguem sua jornada rumo à Montanha da Perdição para destruir o anel e descobrem que estão sendo perseguidos pelo misterioso Gollum. Enquanto isso, Aragorn, o elfo e arqueiro Legolas e o anão Gimli partem para resgatar os hobbits sequestrados e chegam ao reino de Rohan, onde o rei Theoden foi vítima de uma maldição mortal de Saruman.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Senhor dos Anéis: O Retorno do Rei ', 'O olho do inimigo está se movendo.', 2003, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg', 'O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima. Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência. Um exército é reunido por Theoden em Rohan, em mais uma tentativa de deter as forças de Sauron. Enquanto isso, Frodo, Sam e Gollum seguem sua viagem rumo à Montanha da Perdição para destruir o anel.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Velozes & Furiosos 3', 'Desafio em Tóquio, a velocidade vai além da honram, corra para sobreviver.', 2006, 'https://i.ytimg.com/vi/OhhmaNamPSc/hqdefault.jpg', 'Sean Boswell é um piloto de rua que desafia seu rival e bate o carro no fim da corrida. Então, Sean decide se mudar para o Japão em companhia de seu pai para evitar a prisão nos Estados Unidos, já que os rachas não são nada populares com as autoridades. Em Tóquio, ele começa a aprender um excitante e perigoso estilo novo de competir nas ruas. Só que os riscos ficam ainda mais altos quando Sean decide competir com o campeão local e acaba se apaixonando pela namorada dele.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('John wick 2', 'Um novo dia para matar, uma nova prestação de contas com a vida', 2017, 'https://i1.wp.com/espalhafactos.com/wp-content/uploads/2016/12/john-wick-chapter-2-nycc-poster.jpg?fit=1200%2C675&ssl=1', 'Após recuperar seu carro, John Wick (Keanu Reeves) acredita que enfim poderá se aposentar. Entretanto, a reaparição de Santino D Antonio (Riccardo Scarmacio) atrapalha seus planos. Dono de uma promissória em nome de Wick, por ele usada para deixar o posto de assassino profissional da Alta Cúpula, Santino cobra a dívida existente e insiste para que ele mate sua própria irmã, Gianna (Claudia Gerini).', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Como se Fosse a Primeira Vez', 'A arte da conquista diária, todo dia e um dia ideal para se apaixonar', 2004, 'https://trabalhosparaescola.com.br/wp-content/uploads/2019/07/Como-se-fosse-a-primeira-vez.jpg', 'Henry Roth é um veterinário paquerador, que vive no Havaí, e famoso pelo grande número de turistas que conquista. Seu novo alvo é Lucy Whitmore, que mora no local e por quem Henry se apaixona perdidamente. Mas Lucy sofre de falta de memória de curto prazo e, por isso, ela rapidamente se esquece de fatos que acabaram de acontecer. Assim, Henry é obrigado a conquistá-la, dia após dia, para ficar ao seu lado.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Círculo de Fogo', 'A Revolta” fracassa por não entender universo criado por Guillermo del Toro.', 2013, 'https://estalagemnerd.com.br/wp-content/uploads/2018/03/Circulo-de-Fogo-2-49-Estalagem-Nerd-CAPA.jpg', 'Criaturas monstruosas conhecidas como Kaiju começam a emergir do mar. Para combatê-los, a humanidade desenvolve uma série de robôs gigantescos, os Jaegers. Cada um é controlado por duas pessoas por meio de uma conexão neural. Entretanto, mesmo os Jaegers se mostram insuficientes para derrotar os Kaiju. Diante deste cenário, a última esperança é um velho robô, que passa a ser comandado por um antigo piloto e uma pessoa em treinamento.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('No Limite do Amanhã', 'Mas uma oportunidade de salva a humanidade da invasão alienígena', 2014, 'https://is5-ssl.mzstatic.com/image/thumb/XKlagwvmAgZPDgWi6h3lCg/1200x675.jpg', 'Quando a Terra é tomada por alienígenas, Bill Cage é obrigado a juntar-se às Forças Armadas e ir para a linha de frente no dia do confronto final. Inexplicavelmente ele acaba preso no tempo, condenado a reviver esta data repetidamente. A cada morte e renascimento, Cage adquire mais conhecimento e, antecipando os acontecimentos, tem a chance de mudar o curso da batalha com o apoio', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Vingadores', 'Ultimato, recuperando as forças para a batalha épica contra Thanos ', 2019, 'https://www.blogsoestado.com/marciohenrique/files/2019/09/VINGADORES-ULTIMATO-2019.jpg', 'Em Vingadores: Ultimato, após Thanos eliminar metade das criaturas vivas em Vingadores: Guerra Infinita, os heróis precisam lidar com a dor da perda de amigos e seus entes queridos. Com Tony Stark (Robert Downey Jr.) vagando perdido no espaço sem água nem comida, o Capitão América/Steve Rogers (Chris Evans) e a Viúva Negra/Natasha Romanov (Scarlett Johansson) precisam liderar a resistência contra o titã louco.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Ilha do Medo', 'A investigação de Edward Daniels em uma prisão psiquiátrica escondida numa ilha remota', 2010, 'https://www.nivelepico.com/wp-content/uploads/2010/12/ilha-do-medo-1.jpg', '1954. Teddy Daniels (Leonardo DiCaprio) investiga o desaparecimento de um paciente no Shutter Island Ashecliffe Hospital, em Boston. No local, ele descobre que os médicos realizam experiências radicais com os pacientes, envolvendo métodos ilegais e anti-éticos. Teddy tenta buscar mais informações, mas enfrenta a resistência dos médicos em lhe fornecer os arquivos que possam permitir que o caso seja aberto. Quando um furacão deixa a ilha sem comunicação, diversos prisioneiros conseguem escapar e tornam a situação ainda mais perigosa.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Círculo de Fogo 2', 'O Retorno” fracassa por não entender universo criado por Guillermo del Toro.', 2013, 'https://i.ytimg.com/vi/dFrm3hZGdRQ/maxresdefault.jpg', 'Criaturas monstruosas conhecidas como Kaiju começam a emergir do mar. Para combatê-los, a humanidade desenvolve uma série de robôs gigantescos, os Jaegers. Cada um é controlado por duas pessoas por meio de uma conexão neural. Entretanto, mesmo os Jaegers se mostram insuficientes para derrotar os Kaiju. Diante deste cenário, a última esperança é um velho robô, que passa a ser comandado por um antigo piloto e uma pessoa em treinamento.', 1);

insert into tb_review(text,movie_id,user_id)values('O melhor filme de ação',1,2);
insert into tb_review(text,movie_id,user_id)values('O melhor filme de ação, esperando continuação',1,2);
insert into tb_review(text,movie_id,user_id)values('Nota 1000',1,2);
insert into tb_review(text,movie_id,user_id)values('Otimo filme, com um elenco espetacular!',1,2);




